# Generated by Django 5.1.7 on 2025-04-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0002_popularroute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flightoffer",
            name="currency",
            field=models.CharField(default="ANY", max_length=3),
        ),
    ]
