# Generated by Django 5.1.7 on 2025-04-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_customuser_is_email_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="currency",
            field=models.CharField(blank=True, max_length=100, verbose_name="Devise"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="pays",
            field=models.CharField(blank=True, max_length=100, verbose_name="Pays"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="ville",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ville"),
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="currency",
            field=models.CharField(blank=True, max_length=100, verbose_name="Devise"),
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="pays",
            field=models.CharField(blank=True, max_length=100, verbose_name="Pays"),
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="ville",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ville"),
        ),
    ]
