# Generated by Django 5.1.7 on 2025-04-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0004_customuser_currency_customuser_pays_customuser_ville_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="currency",
            field=models.CharField(blank=True, max_length=100, verbose_name="_"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="pays",
            field=models.CharField(blank=True, max_length=100, verbose_name="_"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="ville",
            field=models.CharField(blank=True, max_length=100, verbose_name="_"),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="currency",
            field=models.CharField(blank=True, max_length=100, verbose_name="_"),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="pays",
            field=models.CharField(blank=True, max_length=100, verbose_name="_"),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="ville",
            field=models.CharField(blank=True, max_length=100, verbose_name="_"),
        ),
    ]
