# Generated by Django 5.1.7 on 2025-04-08 16:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flights", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin"), ("O", "Autre")],
                        max_length=1,
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "passenger_type",
                    models.CharField(
                        choices=[
                            ("ADULT", "Adulte"),
                            ("CHILD", "Enfant"),
                            ("INFANT", "Bébé"),
                        ],
                        default="ADULT",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=20, unique=True)),
                (
                    "amadeus_booking_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("CONFIRMED", "Confirmée"),
                            ("PAID", "Payée"),
                            ("CANCELLED", "Annulée"),
                            ("COMPLETED", "Terminée"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="XOF", max_length=3)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OFFICE", "Paiement en agence"),
                            ("ORANGE", "Orange Money"),
                            ("MOOV", "Moov Money"),
                            ("WAVE", "Wave"),
                            ("VISA", "Carte Visa"),
                            ("PAYPAL", "PayPal"),
                            ("MTN", "MTN Money"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "office_appointment_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("raw_booking_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flight_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="flights.flightoffer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "passengers",
                    models.ManyToManyField(
                        related_name="bookings", to="bookings.passenger"
                    ),
                ),
            ],
        ),
    ]
